In [14]:
import numpy as npy
ar = npy.array((1,2,3,4,5,6,7,8,9,10))
print("Array created using tuple : ",ar)
print('ar[0] : ',ar[0])
print(ar[:2])
print(ar[2:5])
print(ar[::2])
print(ar[::3])

Array created using tuple :  [ 1  2  3  4  5  6  7  8  9 10]
ar[0] :  1
[1 2]
[3 4 5]
[1 3 5 7 9]
[ 1  4  7 10]


In [16]:
import numpy as npy
ar_list =npy.array([1,2,3,4,5,6,7,8,9])
print("Array created using list : ",ar_list)
print('ar_list[0] : ',ar_list[0])
print(ar_list[:2])
print(ar_list[2:5])

Array created using list :  [1 2 3 4 5 6 7 8 9]
ar_list[0] :  1
[1 2]
[3 4 5]


In [35]:
import numpy as npy
ar2d = npy.array([[1,2,3,4],[20,30,40,50]])
print(ar2d)
print(ar2d[1,3])
print(ar2d[1:,::2])
Index_arr = ar2d[[1,0,1,0],[1,0,1,1]]
print(Index_arr)
print("Transpose:\n",ar2d.T)

[[ 1  2  3  4]
 [20 30 40 50]]
50
[[20 40]]
[30  1 30  2]
Transpose:
 [[ 1 20]
 [ 2 30]
 [ 3 40]
 [ 4 50]]


In [33]:
import numpy
a = numpy.array((1,2,3,4))
b =numpy.array((4,5,6,7,8,9))
c = numpy.array((10,20,30,40))
print(a+10)
print(a.sum())
print(a+c)
print(numpy.add(a,c))
print(numpy.sum(a))
print(numpy.sqrt(a))
print(a.T)

[11 12 13 14]
10
[11 22 33 44]
[11 22 33 44]
10
[1.         1.41421356 1.73205081 2.        ]
[1 2 3 4]


In [37]:
d = numpy.append(a,b)
d

array([1, 2, 3, 4, 4, 5, 6, 7, 8, 9])

In [38]:
print(numpy.insert(d,2,100))

[  1   2 100   3   4   4   5   6   7   8   9]


In [41]:
print(d.shape)

(10,)


In [43]:
d = numpy.append(a,b,axis =0)
print(d)



[1 2 3 4 4 5 6 7 8 9]


In [46]:

list1= [1,2,3,4]
list2 = [10,20,30]
print(list1)
list1.append(list2)
print(list1)
list1.extend(list2)
print(list1)

[1, 2, 3, 4]
[1, 2, 3, 4, [10, 20, 30]]
[1, 2, 3, 4, [10, 20, 30], 10, 20, 30]


In [55]:
ar = numpy.array((10,20,30,40))
for i in ar:
    print(i)
print("\n")

length= len(ar)
for i in range(length):
     print(ar[i])
print("\n")   

for i, val in enumerate(ar):
    print(i,':',val)

10
20
30
40


10
20
30
40


0 : 10
1 : 20
2 : 30
3 : 40
