In [2]:
import pandas as pan
ar = pan.Series([1,2,3,4])
ar

0    1
1    2
2    3
3    4
dtype: int64

In [102]:
import pandas as pan
import numpy as npy
ar2 = npy.array([[1,1],2,3])
ar = pan.Series(data = ar2, index = ['a','b','c'])
ar

/var/folders/5m/h11gshf125b0gpqn69qmp04h0000gn/T/ipykernel_82241/1205225556.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar2 = npy.array([[1,1],2,3])


a    [1, 1]
b         2
c         3
dtype: object

In [7]:
import pandas as pan
import numpy as npy
ar = npy.array([1,2,3,4])
s = pan.Series(data = ar, index = ['a','b','c','d'], dtype = complex)
print(s)
print(s['b'])


a    1.0+0.0j
b    2.0+0.0j
c    3.0+0.0j
d    4.0+0.0j
dtype: complex128
(2+0j)


In [1]:
import pandas as pan
import numpy as npy
ar = npy.array([10,2,3,4])
s = pan.Series(data = ar, index = [1,2,3,4], dtype = complex)
print(s)
print(s.loc[1])
print(s.iloc[1])

1    10.0+0.0j
2     2.0+0.0j
3     3.0+0.0j
4     4.0+0.0j
dtype: complex128
(10+0j)
(2+0j)


In [17]:
import pandas as pan
df = pan.DataFrame({'Age':[10,20,30],'Name':['A','B','C']})
df


Age Name
0   10    A
1   20    B
2   30    C

In [16]:
print(df)

   Age Name
0   10    A
1   20    B
2   30    C


In [24]:
import numpy as npy
import pandas as pan
ar = npy.array([[1,2,3],[11,22,33]])
print(ar)
df = pan.DataFrame( data = ar)
df

[[ 1  2  3]
 [11 22 33]]


0   1   2
0   1   2   3
1  11  22  33

In [29]:
import numpy as npy
import pandas as pan
ar = npy.array([[1,2,3],[11,22,33]])
print(ar)
df = pan.DataFrame( data = ar, columns = ['A','B','C'], index = [1,2])
df

[[ 1  2  3]
 [11 22 33]]


A   B   C
1   1   2   3
2  11  22  33

In [40]:
import numpy as npy
import pandas as pan
ar = npy.array([[1,2,3],[11,22,33]])
df = pan.DataFrame( data = ar, columns = ['A','B','C'], index = [1,2])
df['A']





A    1
B    2
C    3
Name: 1, dtype: int64

In [39]:
df.values[0,1]

2

In [46]:
df.loc[1]


A    1
B    2
C    3
Name: 1, dtype: int64

In [45]:
df.iloc[0]

A    1
B    2
C    3
Name: 1, dtype: int64

In [94]:
import pandas as pan
import numpy as npy
ar = npy.array([[[1,1],[1,2],[1,3]],[[2,1],[2,2],[2,3]],[[3,1],[3,2],6]])
df = pan.DataFrame( data = ar, columns = ['Combo1','Combo2','Combo3'], index = [1,2,3])
df

/var/folders/5m/h11gshf125b0gpqn69qmp04h0000gn/T/ipykernel_82241/1354737210.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar = npy.array([[[1,1],[1,2],[1,3]],[[2,1],[2,2],[2,3]],[[3,1],[3,2],6]])


Combo1  Combo2  Combo3
1  [1, 1]  [1, 2]  [1, 3]
2  [2, 1]  [2, 2]  [2, 3]
3  [3, 1]  [3, 2]       6